import { IssuedDocumentPaymentsListItemPaymentTerms, IssuedDocumentStatus } from "@fattureincloud/fattureincloud-ts-sdk";

export class Documento {
    id: string; // Identificativo univoco del documento,
    token: string; // Identificativo permanente del documento (rimane lo stesso anche a seguito di modiifche),
    tipo: 'fatture' | 'proforma' | 'ordini' | 'preventivi' | 'ndc' | 'ricevute' | 'ddt' | 'rapporti' | 'ordforn'; // Tipologia del documento = ['fatture' o 'proforma' o 'ordini' o 'preventivi' o 'ndc'],
    id_cliente: string; // Identificativo univoco del cliente (se nullo, il cliente non è presente nell'anagrafica) [solo con tipo!="ordforn"],
    id_fornitore: string; // Identificativo univoco del fornitore (se nullo, il fornitore non è presente nell'anagrafica) [solo con tipo="ordforn"],
    nome: string; // Nome o ragione sociale del cliente/fornitore,
    indirizzo_via: string; // Indirizzo del cliente,
    indirizzo_cap: string; // CAP del cliente/fornitore,
    indirizzo_citta: string; // Città (comune) del cliente/fornitore,
    indirizzo_provincia: string; // Provincia del cliente/fornitore,
    indirizzo_extra: string; // Note extra sull'indirizzo,
    paese: string; // Paese (nazionalità) del cliente/fornitore,
    lingua: string; // Lingua del documento (sigla) = ['it' o 'en' o 'de'],
    piva: string; // Partita IVA cliente/fornitore,
    cf: string; // Codice fiscale cliente/fornitore,
    numero: string; // Numero (e serie) del documento,
    data: Date; // Data di emissione del documento,
    prossima_scadenza: Date; // [Non presente in preventivi e ddt] Indica la scadenza del prossimo pagamento (vale 00/00/0000 nel caso in cui tutti i pagamenti siano saldati),
    valuta: string; // Valuta del documento e degli importi indicati,
    valuta_rate?: string;
    valuta_simbolo?: string;
    valuta_cambio: number; // Tasso di cambio EUR/{valuta},
    prezzi_ivati: boolean; // Specifica se i prezzi da utilizzare per il calcolo del totale sono quelli netti, oppure quello lordi, comprensivi di iva,
    importo_netto: number; // Importo netto del documento (competenze),
    importo_iva: number; // Importo dell'IVA del documento,
    importo_totale: number; // Importo lordo del documento (totale da pagare),
    rivalsa: number; // [Non presente in ddt e ordforn] Percentuale rivalsa INPS,
    importo_rivalsa: number; // [Non presente in ddt e ordforn] Importo rivalsa INPS,
    cassa: number; // [Non presente in ddt e ordforn] Percentuale cassa previdenziale,
    importo_cassa: number; // [Non presente in ddt e ordforn] Importo cassa previdenziale,
    rit_acconto: number; // [Non presente in ddt e ordforn] Percentuale ritenuta d'acconto,
    imponibile_ritenuta: number; // [Non presente in ddt e ordforn] Imponibile della ritenuta d'acconto (percentuale sul totale),
    importo_rit_acconto: number; // [Non presente in ddt e ordforn] Importo ritenuta d'acconto,
    rit_altra: number; // [Non presente in ddt e ordforn] Percentuale altra ritenuta (ritenuta previdenziale, Enasarco etc.),
    importo_rit_altra: number; // [Non presente in ddt e ordforn] Importo altra ritenuta (ritenuta previdenziale, Enasarco etc.),
    marca_bollo: number; // [Non presente in ddt e ordforn] Valore della marca da bollo (0 se non presente),
    oggetto_visibile: string; // [Non presente in ddt] Oggetto mostrato sul documento (precedentemente "oggetto_fattura"),
    oggetto_interno: string; // [Non presente in ddt] Oggetto (per organizzazione interna),
    centro_ricavo: string; // [Non presente in ddt e ordforn] Centro ricavo,
    centro_costo: string; // [Solo in ordforn] Centro di costo,
    note: string; // [Non presente in ddt] Note (in formato HTML),
    nascondi_scadenza?: boolean; // [Non presente in ddt] Nasconde o mostra la scadenza sul documento,
    ddt?: boolean; // [Non presente in ndc e ordforn] Indica la presenza di un DDT incluso nel documento (per i ddt è sempre true),
    ftacc?: boolean; // [Solo se tipo=fatture] Indica la presenza di una fattura accompagnatoria inclusa nel documento,
    id_template: string; // [Solo se tipo!=ddt] Identificativo del template del documento,
    ddt_id_template: string; // [Solo se ddt=true] Identificativo del template del ddt,
    ftacc_id_template: string; // [Solo se ftacc=true] Identificativo del template della fattura accompagnatoria,
    mostra_info_pagamento?: boolean; // [Non presente in ddt e ndc] Mostra o meno le informazioni sul metodo di pagamento sul documento,
    metodo_pagamento: string; // [Solo se mostra_info_pagamento=true] Nome del metodo di pagamento,
    metodo_titoloN: string; // [Solo se mostra_info_pagamento=true] Titolo della riga N del metodo di pagamento (N da 1 a 5),
    metodo_descN: string; // [Solo se mostra_info_pagamento=true] Descrizione della riga N del metodo di pagamento (N da 1 a 5),
    mostra_totali: string; // [Solo per preventivi, rapporti e ordforn] Nasconde o mostra la scadenza sul documento = ['tutti' o 'netto' o 'nessuno'],
    mostra_bottone_paypal?: boolean; // [Solo per ricevute, fatture, proforma, ordini] Mostra il bottone "Paga con Paypal",
    mostra_bottone_bonifico?: boolean; // [Solo per ricevute, fatture, proforma, ordini] Mostra il bottone "Paga con Bonifico Immediato",
    mostra_bottone_notifica?: boolean; // [Solo per ricevute, fatture, proforma, ordini] Mostra il bottone "Notifica pagamento effettuato",
    lista_articoli: DocArticolo[]; // Lista degli articoli/righe del documento,
    lista_pagamenti: DocPagamento[]; // [Non presente in preventivi, ddt e ordforn] Lista delle tranches di pagamento,
    ddt_numero: string; // [Se ddt=true] Numero del ddt (se tipo="ddt" corrisponde al campo "numero"),
    ddt_data: Date; // [Se ddt=true] Data del ddt Numero del ddt (se tipo="ddt" corrisponde al campo "data"),
    ddt_colli: string; // [Se ddt/ftacc=true] Numero di colli specificato nel ddt,
    ddt_peso: string; // [Se ddt/ftacc=true] Peso specificato nel ddt,
    ddt_causale: string; // [Se ddt/ftacc=true] Causale specificata nel ddt,
    ddt_luogo: string; // [Se ddt/ftacc=true] Luogo di spedizione specificato nel ddt,
    ddt_trasportatore: string; // [Se ddt/ftacc=true] Dati trasportatore specificati nel ddt,
    ddt_annotazioni: string; // [Se ddt/ftacc=true] Annotazioni specificate nel ddt,
    link_doc: string; // [Solo se tipo!=ddt] Link al documento in formato PDF,
    link_ddt: string; // [Solo se ddt=true] Link al ddt in formato PDF,
    link_ftacc: string; // [Solo se ftacc=true] Link alla fattura accompagnatoria in formato PDF,
    link_allegato: string; // [Solo se è presente un allegato] Link al file allegato,
    bloccato?: boolean; // Indica se il documento è bloccato (e di conseguenza non può essere modificato o eliminato),
    PA?: boolean; // [Solo per fatture e ndc elettroniche, vale sempre "true"] Indica che il documento è nel formato FatturaPA,
    PA_pec?: string; 
    PA_tipo_cliente: string; // [Solo se PA=true] Indica la tipologia del cliente: Pubblica Amministrazione ("PA") oppure privato ("B2B") = ['PA' o 'B2B'],
    PA_tipo: string; // [Solo se PA=true] Tipo di documento a cui fa seguito la fattura/ndc in questione = ['ordine' o 'convenzione' o 'contratto' o 'nessuno'],
    PA_numero: string; // [Solo se PA=true] Numero del documento a cui fa seguito la fattura/ndc in questione,
    PA_data: Date; // [Solo se PA=true] Data del documento a cui fa seguito la fattura/ndc in questione,
    PA_cup: string; // [Solo se PA=true] Codice Unitario Progetto,
    PA_cig: string; // [Solo se PA=true] Codice Identificativo della Gara,
    PA_codice: string; // [Solo se PA=true] Codice Ufficio della Pubblica Amministrazione,
    PA_esigibilita: string; // [Solo se PA=true] Esigibilità IVA e modalità di versamento (I=immediata, D=differita, S=split payment, N=non specificata) = ['I' o 'D' o 'S' o 'N'],
    PA_modalita_pagamento: string; // [Solo se PA=true] Modalità di pagamento (vedi tabella codifiche sulla documentazione ufficiale),
    PA_istituto_credito: string; // [Solo se PA=true] Nome dell'istituto di credito,
    PA_iban: string; // [Solo se PA=true] Codice IBAN del conto corrente del beneficiario,
    PA_beneficiario: string; // [Solo se PA=true] Beneficiario del pagamento,
    PA_ts?: boolean; // [Solo se PA=true] Indica che la fattura/ndc elettronica è stata inviata tramite il servizio FEPA TeamSystem,
    PA_ts_stato: string; // [Solo se PA_ts=true] Stato di invio della fattura/ndc,
    split_payment?: boolean; // [Solo per fatture, ndc e proforma NON elettroniche, vale sempre "true"] Indica che il documento applica lo split payment
    liguaggio?: { nome: string; codice: string; };
}

export class DocArticolo {
    id: string; // Identificativo del prodotto (se nullo, non è presente tra i prodotti),
    codice: string; // Codice prodotto,
    nome: string; // Nome articolo,
    um: string; // Unità di misura per il prodotto,
    quantita: number; // Quantità di prodotto,
    descrizione: string; // Descrizione del prodotto,
    categoria: string; // Categoria del prodotto (utilizzata per il piano dei conti),
    prezzo_netto: number; // Prezzo unitario netto (IVA esclusa),
    prezzo_lordo: number; // Prezzo unitario lordo (comprensivo di IVA),
    valore_iva: number; // Valore IVA (percentuale),
    desc_iva: string; // Descrizione della tipologia di IVA,
    tassabile: boolean; // [Non presente in ordforn e ddt] Indica se l'articolo è imponibile,
    sconto: number; // [Non presente in ddt] Sconto (percentuale),
    applica_ra_contributi: boolean; // [Non presente in ordforn e ddt] Indica se a questo articolo vengono applicate ritenute e contributi,
    ordine: number; // Ordine dell'articolo in fattura (ordinamento ascendente),
    sconto_rosso: boolean; // [Non presente in ordforn e ddt] Evidenzia l'eventuale sconto in fattura,
    in_ddt: boolean; // [Non presente in ordforn e ddt] Indica se l'articolo è incluso nel DDT (se presente, altrimenti non è significativo),
    magazzino?: boolean; // Indica se viene movimentato il magazzino (true: viene movimentato; false: non viene movimentato) [Non presente se in ordforn e ddt, oppure se il prodotto non è collegato all'elenco prodotti, oppure la funzionalità magazzino era disattiva al momento della creazione del documento]
}

export class DocPagamento {
    data_scadenza: Date; // Data di scadenza del pagamento,
    importo: number; // Importo del pagamento,
    metodo: string; // Conto di saldo = ['not' o 'rev' o il nome del conto] ('not' indica che non è stato saldato, 'rev' che è stato stornato),
    data_saldo: Date; // Data del saldo dell'importo indicato (se avvenuto)
    stato: IssuedDocumentStatus;
    termini_di_pagamento: IssuedDocumentPaymentsListItemPaymentTerms
}